---
- name: Set KeyValueStore Port
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/server.conf"
    section: kvstore
    option: "port"
    value: "{{ splunk.kvstore.port }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"

- name: Adjust server.conf permissions (Windows)
  file:
    path: "{{ splunk.home }}/etc/system/local/server.conf"
    mode: 0644
  when:
    - ansible_system is match("CYGWIN*|Win32NT")