- name: Set general pass4SymmKey
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/server.conf"
    section: "general"
    option: "pass4SymmKey"
    value: "{{ splunk.pass4SymmKey }}"
    mode: 0644
  notify:
    - Restart the splunkd service